name: 'loven_stats'
version: '1.0.0'
config-version: 2

profile: 'loven_stats'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  loven_stats:
    marts:
      +materialized: table
      product:
        +materialized: incremental
